baseURL = "https://megate.ch/"
languageCode = "en-us"
title = "Megatech"
theme = "megatech-paper"
enableGitInfo = true

[params]
  AuthorName = "Alexander Rothman"
  GitHubUser = "gn0mesort"
  mainSections = [ ]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
      codeFences = false
