baseURL = "https://megate.ch/"
languageCode = "en-us"
title = "Megatech"
theme = "megatech"
enableGitInfo = true

[params]
  AuthorName = "Alexander Rothman"
  GitHubUser = "gn0mesort"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
