baseURL = "https://megate.ch/"
languageCode = "en-us"
title = "Megatech"
theme = "megatech"
enableGitInfo = true

[markup]
  [markup.highlight]
    tabWidth = 2
    style = "dracula"
    noClasses = false
